### ISSUE TITLE
mdatLength not greater than chunkLength

### ISSUE THREAD

**Issue by joravkumar** [kevinGodell/live-stream-media-source-extensions#2]
Hey kevin,
I am facing this issue while the running `index.js`.
Help me out here?

Thanks in advance.
![ffmpeg error](https://user-images.githubusercontent.com/42232691/84625818-a4a00500-af01-11ea-9392-1f087e157190.jpg)

**Comment by kevinGodell** [comment]
The mp4segmenter.js was an experiment that lead to the module "mp4frag" that can be installed `npm install mp4frag`. I pushed a new commit that uses the updated code. Hopefully it works better for you.

**Comment by joravkumar** [comment]
Thanks. 
It works!!

**Comment by joravkumar** [comment]
Thanks.
It works!!
