### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by karlbrowns** [kevinGodell/live-stream-media-source-extensions#3]
Hi,
First of all - it worked 1st time, out of the box - thank you.

However, there are FFmpeg options to reduce start up time, but even with these in place (probesize being the main one) I still find latency between camera and web about 3 seconds.  Is there any place I can look to reduce this further?

Thanks,
Simon

**Comment by kevinGodell** [comment]
I will assume we are talking about mp4 streaming. 

The nature of mp4 muxing requires complete segments before ffmpeg can output the piece. If the segment is 2 seconds duration, then that segment will be delayed by atleast 2 seconds plus the transport time and adding it to the player. 

One way to reduce latency is to encode the fragmented mp4 at the expense of high cpu load and make the segments shorter duration. 

The other way is the set the video source to have shorter duration segments and stream copy which be use lower cpu load. Most cameras can go no lower than 2 seconds segment duration. In the cam, it might be called iframe interval or gop.

**Comment by karlbrowns** [comment]
Ok, I have control over the GOP size but for other reasons don't really want to reduce it.
Thanks for the quick reply.
